#!/bin/bash
function resetVar() {
	echo "Resetting variables"
	newLocation=(0 0 0 0 0 0 0 0 0 0 0)
	cp ~/L.A.R.K/CORE/mapFiles/mapLocked ~/L.A.R.K/CORE/mapFiles/map
	rm ~/L.A.R.K/CORE/inventory/*
	#location tracker reset, inventory and map reset
	}

#save screen
tput smcup

# Display until selection == 0
while [[ $REPLY != 0 ]]
do
clear
  cat <<EOF
	     MAIN MENU
	═══════════════════
	1. New Game
	2. Continue
	3. Help
	0. Quit

EOF

read -p "Enter Selection [0-3]: " selection
	case $selection in
	1) read -p "Enter Your Name: " userName
		clear
		cat <<EOF
	  Skip Cutsene?
	═══════════════════
	1. NO
	2. YES
	0. Back
EOF
		read -p "Enter Selection [0-2]: " selection2
		case $selection2 in
			1) ~/L.A.R.K/CORE/scripts/./startCutscene
			;;
			2) echo "Will skip cutscene and start game)"
			;;
			0) tput rmcup
			;;	
			*) echo "Invalid"
			;;
		esac
	;;
	2) read -p "Enter Your Name: " userName
		if [ $(gawk '{ print $1}' ./currentPlayer.dat) = $userName ]
			then
				echo "Welcome back $userName"
				sleep 2
				#INSERT SCRIPT TO LOAD SAVE FILE
		else
			echo "No Save File Found"
			tput rmcup
		fi
	;;
	0) break
	   ;;
esac
done

tput rmcup
echo "Program Terminated"
	
