#!/bin/bash
clear
echo "A strange writing has been carved into the cave wall. There are also spots with dozens of small claw marks leading down the right path..."
sleep 5
tput bold; echo -n "LaCo: "; tput sgr0; echo "I can't get a direct translation, but it appears to be some kind of doomsday quote..."
sleep 5














































































# ~wall is a script, use the source command to interact with it: . walls
# use the function "LaCo" to view your commands if you need help

