#!/bin/bash
sleep 2
tput bold ; echo "YOU: "; tput sgr0;
REPLY="X"
while [[ $REPLY != 0 ]]; do
cat <<EOF
	1. Where are we..? What happened?
	2. What do I do..?
	3. Can you help me?
	0. Alright, I think I've got it.
EOF
echo
read -p " " selection
case $selection in
	1) tput bold ; echo -n "YOU: "; tput sgr0; echo "Where are we..? What happened?"
	sleep 3
	tput bold ; echo -n "LaCo: "; tput sgr0; echo "It looks like we activated some sort of defense system built into the planet."
	sleep 5
	echo "I can't access my counterparts... There are no vital readings from any of the squad..."
	sleep 5
	echo "It looks like you're the only one who survived the attack. The debris must have knocked us just out of the direct path of the beam. Your vitals appear to be stabilizing, no indication of any concussion or serious injury.
"
	sleep 15
	;;
	2) tput bold ; echo -n "YOU: "; tput sgr0; echo "What do I do..?"
	sleep 3
	tput bold ; echo -n "LaCo: "; tput sgr0; echo "Private 0726 will send a rescue team to us in 5 DAYS."
	sleep 5
	echo "Until then, you'll need to survive and find a way to warn the rescue team of the defense system. If you can get to high ground, I might be able to fast stream a signal before they arrive.
"
	sleep 10
	;;
	3) tput bold ; echo -n "YOU: "; tput sgr0; echo "Can you help me?"
	sleep 3
	tput bold ; echo -n "LaCo: "; tput sgr0; echo "I'll do everything I can to help you survive until the rescue team arrives."
	sleep 5
	echo "I'm picking up bits of ancient data scrambled in the planet's atmosphere. Here's what I've collected so far:
"
	sleep 7
	echo -n  "
Type "; tput bold; echo -n  "ls"; tput sgr0; echo -n " to look around. This will show you anything in your immediate area.
New locations will be "; printf "\x1b[38;2;85;85;255mBlue\x1b[0m"; echo -n ". These are called directories.
"
	sleep 1
	echo -n  "
Anything that you can interact with will be"; printf "\x1b[38;2;85;255;85m Light Green\x1b[0m"; echo -n " and begins with a '~'.
These are called scripts.
"
	sleep 1
	echo -n "
Objects that you can look at will be the default color of your text. These are called files. Type "; tput bold; echo -n "cat "; tput sgr0; echo -n "followed by the file to get a better look at it. Ex. 'cat food'

"
	tput cnorm
	sleep 8
	;;
	0)tput bold ; echo -n "YOU: "; tput sgr0; echo "Alright, I think I've got it."
	sleep 3
	 tput bold ; echo -n "LaCo: "; tput sgr0; echo -n " I've mapped out a few areas that might be important. I'll update it as you discover new locations. To view the map, call the map function by typing "; tput bold; echo -n "Map"; tput sgr0; echo ". And just one more thing."
sleep 10
echo -n "[ Day 0 | Hunger [   ] | Beach ]$ 
     ^ This is your day tracker. It'll let you know how many days have passed. You'll need to use the function "; tput bold; echo -n "rest "; tput sgr0; echo -n "to sleep and skip to the next day.
"
sleep 7
echo -n "[ Day 0 | Hunger [   ] | Beach ]$
	   ^ Be careful though, you'll need to eat at least once a day to survive. If you don't eat for two days, you'll starve to death. Food can be collected as you explore.
"
sleep 10
echo "[ Day 0 | Hunger [   ] | Beach ]$
			  ^ This is your current location.
"
sleep 3
echo -n "The first day will be difficult, so I'll be with you every step of the way. Whenever I have information for you, you'll see my name when you look around. Type 'cat LaCo' to read my file! Type ls to get started. Good luck!" 
echo "
"
	sleep 15	
	break
	;;
esac
done
clear
